### ISSUE TITLE
Custom web directory layout

### ISSUE THREAD

**Issue by gregpardo** [awetzel/reaxt#1]
So I was trying to get [flux-react-router-example](https://github.com/gaearon/flux-react-router-example) working with this and it seems to have a different directory structure and a different webpack setup. Any idea if something like this could be supported? 

It seems that according to [client_entry_addition.js](https://github.com/awetzel/reaxt/blob/master/priv/commonjs_reaxt/client_entry_addition.js) that this folder is hard coded. Could this be something worth customizing or am I going about the process all wrong?

**Comment by awetzel** [comment]
Hello Greg,
You can use any webpack configuration you want. You just have to know that reaxt will modify it to add hot loading plugin if necessary, to add server side associated configuration and to add a small addition to client entries. So you only have to care about your application specific config in your webpack.config. So if you take *flux-react-router-example* : 
-    `webpack-dev-server/client?http://localhost:3000', 'webpack/hot/only-dev-server'` are unnecessary
-  `new webpack.HotModuleReplacementPlugin()` is not necessary either
- the "production" config should be include directly in the webpack.config with a test for Mix environment (see last point of reaxt readme).

So do not reuse a webpack config from somewhere... unfortunately they actually often mix very specific configurations about the dev environment and the server environment. My goal in reaxt was to make sure these configurations are distinct from the "business" configuration. 
- https://github.com/awetzel/reaxt/blob/master/priv/commonjs_reaxt/server.webpack.config.js define the server side configuration from the client one : remove externals, take the server rendering code as only entry, compile in "node" mode.
- https://github.com/awetzel/reaxt/blob/master/priv/commonjs_reaxt/client.webpack.config.js adds the server specific entry to your client entries 
- the *hot* loading compiler add the specific hot loading configuration : https://github.com/awetzel/reaxt/blob/master/priv/commonjs_reaxt/webpack_server.js#L6-L13  , it also remove externals because it makes some hot loader fails (so do not use hot loading in production)

Finally about the directory layout, currently there are 2 constraints : 
- that a `web` directory should be at the root of the mix project where you are compiling the JS, and this web directory should contain NPM and Webpack configuration
- that `web/components` contains all the modules that will be called by `Reaxt.render!`, all these modules will be automatically included on the server and the client JS. 

Allowing a different directory structure would make the code much more complicated since all the components from the JS and Elixir side have to know where to find the main "node_modules" and the shared components between client and server. 

I will see when I find time if Reaxt can be more flexible about this without making it "spaghetti" :) 

Have a good day

**Comment by gregpardo** [comment]
Thanks for the lengthy explanation. I know it's a fairly new project so I see how there are some constraints. Perhaps just putting the the web and the components directory in a config variable with default fallbacks would work?

**Comment by awetzel** [comment]
Currently it is kind of complicated since it needs `require(` to be dynamic, and in this case webpack will require the entire directory...

I will see if we can precompile the webpack config...

**Comment by gregpardo** [comment]
What about placing a '.reaxt' file or something in the root directory that the module loads in it's config from? This way the actual required module is static but its config is loaded in from a specific file from a specific directory.
